### ISSUE TITLE
what are some cool projects you are working on?

### ISSUE THREAD

**Issue by ghost** [seanpierce/ama#1]

**Comment by seanpierce** [comment]
Hey @rylearn!

I'm currently learning **python**, which is something I've been meaning to do for awhile. With this, I'm attempting to write my own password management app called <a href="https://github.com/seanpierce/passman">passman</a>. It's a lot of fun, but I'm having some challenges understanding the proper configurations for the setup.py script.

I've also been getting back into <a href="https://puredata.info/">pure data</a>, which I haven't used in years, but I have nothing thats ready to share yet.

Thanks for asking!

ps: @rylearn - I'm not smiling in my profile pic because I don't want everyone to know that I'm missing all my teeth
